sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
  - openssl aes-256-cbc -K $encrypted_163079534ea5_key -iv $encrypted_163079534ea5_iv -in .gce_auth.json.enc -out .gce_auth.json -d
    # Ansible doesn't play well with virtualenv
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine

install:
  - sudo pip install docker-py
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - git checkout https://github.com/ansible/ansible.git 
  - cd ansible && git submodule update --init 
  - cd lib/ansible/modules/core && git checkout devel
  - cd ../extras && git checkout devel
  - cd && source ansible/hacking/env-setup 
  - ansible --version

script:
  - ansible-playbook test/lnmp_stack.yml 

after_script:
  # Cleanup
